#!/bin/sh /etc/rc.common
START=50

run_c3h()
{
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local domain
		local ifname
		local reconect
		
		config_get username $1 username
		config_get password $1 password
		config_get ifname $1 ifname
		config_get reconect $1 reconect
		
		
		c3h-client $username $password $ifname $reconect &
		
		echo "c3h Client has started."
	fi
}

start()
{
	config_load c3hclient
	config_foreach run_c3h login
}

stop()
{
	killall c3h-client
	killall udhcpc
	
	echo "c3h Client has stoped."
}
