#!/bin/sh /etc/rc.common
START=50

run_njit()
{
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local domain
		local ifname
		local reconect
		
		config_get username $1 username
		config_get password $1 password
		config_get domain $1 domain
		config_get ifname $1 ifname
		config_get reconect $1 reconect
		
		
		# if [ "$domain" != "" ]; then
			# c3h-client $username@$domain $password $ifname &
		# else
			c3h-client $username $password $ifname $reconect &
		# fi
		
		echo "NJIT Client has started."
	fi
}

start()
{
	config_load njitclient
	config_foreach run_njit login
}

stop()
{
	killall c3h-clientt
	killall udhcpc
	
	echo "NJIT Client has stoped."
}
